### PR TITLE
I translated chapter 5 in italian.

### PR DESCRIPTION
**Pull request by andreialex6**

### CODE REVIEW

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Please translate the code (including comments) and use Rust 2021.

**Comment by andreialex6** [comment]
Thank you for your suggestions, I resolved them !

**Comment by alexandruradovici** [comment]
Esti vorbitor de limba italiana?

**Comment by ghost** [comment]
This was merged to upstream in its current state: https://github.com/richardanaya/tour_of_rust/pull/505

**Pull request closed without merging**
