### PR TITLE
Fix typos in translation of chapter 1 in Romanian 🇷🇴

### PR DESCRIPTION
**Pull request by alx-sima**

### CODE REVIEW

**Comment by mariapana** [comment]
There is one more typo on line 1. "Ideiile" should be "Ideile".

**Comment by alx-sima** [comment]
Will do

joi, 11 ian. 2024, 17:49 Maria Pana ***@***.***> a scris:

**Comment by alexandruradovici** [comment]
Please send this to upstream and place a link to it here.

**Comment by alx-sima** [comment]
Opened pull request [here](https://github.com/richardanaya/tour_of_rust/pull/495)

**Pull request closed without merging**
